#title in header
title: "Hello World."

#main info
#owner
owner: "I am Jin Fang"
email:
info: "A PhD student in USTC."
#description
desc: "My research interest lies in the field of distributed systems and computer networks. Currently I am working on programmable networks."

#menu
menu:
  Resume: /resume

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: USTC-INT
placelink: http://staff.ustc.edu.cn/~xuhongli/int/
github: https://github.com/Fangjin98
outlook: mailto:Fangjin98@outlook.com
counter: false
# Misc
nanobar: /js/nanobar.min.js
switch_light: 🌑
switch_dark: ☀️

# favicon
favicon: /images/favicon.png
# thumbnail
# thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
# disqus_enabled: false
# disqus_shortname: https-adisaktijrs-github-io

mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML