title: "Hello World."

owner: "I am (Joey) Jin Fang"
info: "A PhD student, a coder, a powerlifting amateur..."
desc: "My research interest lies in programmable network, in-network computing, and distributed training system. In my spare time, I write C# and Swift codes. Hope my powerlifting record can reach 1323 lbs.
"
email: Fangjin98@outlook.com
menu:
  About: /about
  Posts: /archives
  CV: /pdf/resume.pdf
  

#index/main page max show posts (in number)
max_post: 3

# Colors use hex color without #
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: USTC-INT
placelink: https://int-ustc.github.io/index.html
github: https://github.com/Fangjin98
outlook: mailto:Fangjin98@outlook.com
sspai: https://sspai.com/u/km1o497a/posts
jike: https://m.okjike.com/users/835fc07f-a5e2-4762-936a-d17d0cf7bbfd
rss: /atom.xml
counter: false

# Misc
nanobar: /js/nanobar.min.js
switch_light: 🌑
switch_dark: ☀️

favicon: /images/favicon.png
# thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML